pipeline:
  name: test-harness
  identifier: testharness
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: heidargit
        repoName: test-harness
        build: <+input>
  stages:
    - stage:
        name: bikin-php.html
        identifier: bikinphphtml
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: heidargit
                    repoName: test-harness
                    build:
                      type: branch
                      spec:
                        branch: main
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
