pipeline:
  name: test-harness
  identifier: testharness
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: heidargit
        repoName: test-harness
        build: <+input>
  stages:
    - stage:
        name: bikin-php.html
        identifier: bikinphphtml
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: |-
                      touch index.html
                      echo "hai sayang aku" > index.html
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
